services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve  # Startet den Server im Vordergrund
    depends_on:
      - ollama-init

  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-init
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      sh -c "
        ollama serve & 
        sleep 5 &&
        ollama pull gemma3:4b &&
        ollama pull gemma3:1b
      "
    restart: "no"
  backend:
    image: ${ECR_REGISTRY}/ollama-chat-backend:${IMAGE_TAG}
    build: ./backend
    container_name: backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434

  frontend:
    image: ${ECR_REGISTRY}/ollama-chat-frontend:${IMAGE_TAG}
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000

volumes:
  ollama_data:
