version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000

volumes:
  ollama_data:
